name: Project Manager who pretends he can code
description: select _ from random_thoughts
meta_description: 

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 5
baseurl: /
domain_name: 'http://geerttheys.com'
google_analytics: 'UA-18869272-1'

# Details for the RSS feed generator
url:            'http://geerttheys.com'
author:         'Geert Theys'

exclude: ['config','Rakefile','LICENSE.txt','README.md', 'Gemfile.lock', 'Gemfile']